---
- include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'

- include: install.yml
  tags: lvm_install

- include: config.yml
  tags: lvm_config
